### ISSUE TITLE
Ширина контента

### ISSUE THREAD

**Issue by alexey-pd** [MityaDV/automation_gulp#1]
https://github.com/MityaDV/automation_gulp/blob/17b5f8486a8ddf1e56e210b2737a7d4c5d67efba/source/sass/base/mixins.scss#L2

desktop лучше поделить в 2 шага на 1280 и 1600

**Comment by MityaDV** [comment]
Согласен, спасибо учту.

**Comment by alexey-pd** [comment]
чтобы не вызывать по 3 миксина в каждом блоке...
```
@mixin inner {
  width: 100%;
  margin: 0 auto;
  padding: 0 $padding_mobile;
  box-sizing: border-box;
}

@mixin fixed_inner() {
  @include inner();

  @media (min-width: 768px) {
     padding: 0 $padding_tablet;
  }

  @media (min-width: 1280px) {
     width: 1280px;
     padding: 0 $padding_desktop;
  }

  @media (min-width: 1600px) {
     width: 1600px;
     padding: 0 $padding_wide;
  }
}
```
hmm you like mixins?

![image](https://user-images.githubusercontent.com/12380196/70146858-204c0a00-16b4-11ea-81db-fdc1b62f38cf.png)

**Comment by MityaDV** [comment]
<meta name="viewport" content="width=device-width, initial-scale=1"> По моему без этого мета тега не очень работает, а в общем прикольно, очень удобно   С уважением Дмитрий. От: Aleksei PudnikovОтправлено: 4 декабря 2019 г. в 15:36Кому: MityaDV/automation_gulpКопия: Dmitry Kovalkov; State changeТема: Re: [MityaDV/automation_gulp] Ширина контента (#1) чтобы не вызывать по 3 миксина в каждом блоке...@mixin inner {   width: 100%;   margin: 0 auto;   padding: 0 $padding_mobile;   box-sizing: border-box; }   @mixin fixed_inner() {   @include inner();     @media (min-width: 768px) {      padding: 0 $padding_tablet;   }     @media (min-width: 1280px) {      width: 1280px;      padding: 0 $padding_desktop;   }     @media (min-width: 1600px) {      width: 1600px;      padding: 0 $padding_wide;   } } hmm you like mixins?—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
